### ISSUE TITLE
Arabic not printing in Cashino PTP-II printer

### ISSUE THREAD

**Issue by fahmidul** [sanxy/Printooth#2]
I was trying to print Arabic with CHARCODE_ARABIC_CP720, CHARCODE_ARABIC_WIN_1256 and CHARCODE_ARABIC_FARISI. But getting this unexpected [print](https://i.ibb.co/wzL3P5d/Whats-App-Image-2023-01-18-at-7-00-18-PM.jpg)!

    `add(
            TextPrintable.Builder()
                .setText("العربية")
                .setCharacterCode(DefaultPrinter.CHARCODE_ARABIC_CP720)
                .setNewLinesAfter(1)
                .build()
        )

        add(
            TextPrintable.Builder()
                .setText("العربية")
                .setCharacterCode(DefaultPrinter.CHARCODE_ARABIC_WIN_1256)
                .setNewLinesAfter(1)
                .build()
        )

        add(
            TextPrintable.Builder()
                .setText("العربية")
                .setCharacterCode(DefaultPrinter.CHARCODE_ARABIC_FARISI)
                .setNewLinesAfter(1)
                .build()
        )`

**Comment by sanxy** [comment]
You can log the issue on the actual library [here](https://github.com/mazenrashed/Printooth/issues?q=is%3Aopen+is%3Aissue)

**Comment by fahmidul** [comment]
> You can log the issue on the actual library [here](https://github.com/mazenrashed/Printooth/issues?q=is%3Aopen+is%3Aissue)

Okay, Thanks
